### ISSUE TITLE
Express fields in Talk Detail page, if value(s) exist

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#388] opened 2015-06-18 18:09 UTC

**Comment by wolever** [comment] 2015-07-30 18:12
Ewa linked me here because I suspect I asked for this, but I don't recall the specifics. Which fields are these? Or should I dig through my notes to figure that out?

**Comment by dpoirier** [comment] 2015-07-30 18:30
If you have notes, that would be helpful. We don't seem to have a record of what "Express fields" meant.  Or even if Express here is an adjective or a verb :-)

**Comment by wolever** [comment] 2015-08-17 02:34
See the "talk video", "talk slides", and "talk assets" fields in https://github.com/PyCon/pycon/issues/387 — if they exist, they should be shown somewhere on the talk details page.

Use case: a conference attendee wants to find the video for a talk. They navigate to the schedule, click the talk, and are able to find a link to the video.

**Comment by dpoirier** [comment] 2015-08-17 13:32
Duplicate of #386.

**Closed by dpoirier** 2015-08-17 13:32 UTC
Labels: Need more details
