### ISSUE TITLE
Express fields in conference.json and admin

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#387] opened 2015-06-18 18:08 UTC

**Comment by wolever** [comment] 2015-07-30 18:13
As on #388 — which fields are these? Or should I be letting you know here?

**Comment by dpoirier** [comment] 2015-07-30 18:31
Same as #388, if you can help, please.

**Comment by wolever** [comment] 2015-08-17 02:32
Okay! For conference.json and admin:

- Add the following fields to each talk slot:
  - Talk video URL: likely a PyVideo link
  - Talk slides URL: likely a SpeakerDeck link
  - Talk assets URL: likely a GitHub link
- Those fields should exist in the /schedule/conference.json feed
- There should be an API which I can use to update those URLs
  - it should be as simple as possible, since I'll call it from scripts
  - I don't care what it looks like, so long as I can call it with 3 lines of requests (ex, no oauth or anything complex)
  - An auth check for User.is_staff / User.is_superuser should be sufficient.
- Those fields should be editable from the django admin
- If present and non-empty, they should be shown on the talk description page

The use case here: I've got a collection of scripts which manage uploading slides to SpeakerDeck, videos to YouTube, etc, and I need to close the loop and have those push the appropriate URLs back into the main website.

**Comment by dpoirier** [comment] 2015-08-17 13:33
Duplicate of #387.

**Closed by dpoirier** 2015-08-17 13:33 UTC
Labels: Need more details
