### ISSUE TITLE
When viewing pages, I can scroll to the right fairly far

### ISSUE THREAD

**Issue by sigmavirus24** [PyCon/pycon#368] opened 2015-01-10 04:01 UTC
Hey all, 

I noticed while viewing https://us.pycon.org/2015/community/sprints/ that on both Firefox 34 and Chrome 39.0.2171.95 I can scroll to the right of the page and there doesn't appear to be content there to cause it.

This does **not** happen on the home page for PyCon. I looked for other pages quickly though and found it happening on:

- https://us.pycon.org/2015/community/sprints/ (same as above)
- https://us.pycon.org/2015/schedule/
- https://us.pycon.org/2015/schedule/talks/
- https://us.pycon.org/2015/about/what-is-pycon/
- https://us.pycon.org/2015/sponsors/
- https://us.pycon.org/2015/venue/hotels/

I didn't check every page but I tried to check at least one from each of the drop-downs/categories.

If you cannot reproduce this and need more information, let me know.

**Comment by sigmavirus24** [comment] 2015-01-12 20:27
@rebecca-caktus this can probably be closed (soon).

**Comment by rebecca-caktus** [comment] 2015-01-13 13:36
Deployed to production. Thanks again!

**Comment by rebecca-caktus** [comment] 2015-01-19 15:01
I've reverted this fix temporarily due to a visible regression on the schedule page header. 

I believe that the code that was removed for this ticket was intended to fix the schedule page header. We're looking for an alternative way to fix the schedule page header problem so that this bug can be solved too.

**Comment by brandon-rhodes** [comment] 2016-01-18 15:40
As this does not appear to be an issue for the new 2016 version of the web site, I am closing this issue unless we see the symptom reappear on the new site.

**Closed by brandon-rhodes** 2016-01-18 15:40 UTC
