### ISSUE TITLE
Applicant Receipt Upload Interface

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#384] opened 2015-06-18 18:00 UTC

**Comment by dpoirier** [comment] 2015-07-23 11:42
What data does the user need to provide along with the uploaded file?

**Comment by lvh** [comment] 2015-07-27 17:24
Hey @dpoirier! Thanks for working on this.

Ideally, they'd put in a USD amount. Right now, this process involves them e-mailing me documents, and me opening them, checking the amount, converting to USD as necessary, and then saving them.

For accounting/tax reasons, their expenses need to cover their grant. It'd be cool if the website showed this (since it knows about both the grant size and the sum of all expenses), but that's not a critical feature. Since we have CSV export, I can totally do that manually :)

I'm the emeritus chair, so feel free to ping me if you have any further FA specific things :) @ashfall is the new FA chair, she should probably also get pinged :)

**Comment by dpoirier** [comment] 2015-07-28 13:20
@lvh @ashfall 

Do you want any text to go with the receipt upload?  I was assuming you'd want things like what the receipt was for, maybe a date, that kind of thing?

besides just uploading receipts, what do applicants need to do with them? do they need a list of uploaded receipts?  do they need to be able to delete them?  edit them?

**Comment by lvh** [comment] 2015-07-28 14:58
The minimal feature set is an append-only upload field + dollar amount field. A description field would be a cool extra, and I guess it wouldn't be that much more work. Editing does happen occasionally, but it's fine if that's just the admins doing that through the Django admin interface or something: that's a rare event, and it's important we know when this stuff changes & why :)

**Comment by dpoirier** [comment] 2015-07-28 16:41
Okay @dchukhin let's not do delete or edit then, but I think we can add a description field quite easily so let's do that.

**Comment by dchukhin** [comment] 2015-07-28 18:39
sounds good; user will not have the ability to delete their uploaded receipts, but will be asked to provide a desription

**Comment by dpoirier** [comment] 2015-07-29 14:18
@lvh @ashfall under what circumstances should we show the "upload receipts" button to users on their dashboard?  I would think they should have applied for aid and have accepted an offer (application is in "accepted" state); is that it?

**Comment by ashfall** [comment] 2015-08-02 19:08
That sounds about right: They should have applied for aid, we should've extended a grant offer, and they should've accepted our offer of the grant.

Thanks for working on this!

**Comment by lvh** [comment] 2015-08-02 22:03
Confirmed.

**Comment by dpoirier** [comment] 2015-08-03 11:39
@dchukhin there you go, application should have status STATUS_ACCEPTED to show the upload receipts button.

**Comment by dchukhin** [comment] 2015-08-03 15:40
thanks; this has been updated in the pull request

**Comment by dpoirier** [comment] 2015-08-10 18:25
Fixed in #427.

**Closed by dpoirier** 2015-08-10 18:26 UTC
Labels: has pull
