### ISSUE TITLE
API endpoint for session staff details

### ISSUE THREAD

**Issue by wolever** [PyCon/pycon#483] opened 2015-08-17 02:36 UTC
I'd like an API endpoint which will return the session chairs and runners. Whatever is the absolute simplest to implement which I can cross reference against the conference.json feed:

    GET /schedule/session-staff.json
    [
        {
            "conf_key": 123, // fk into conference.json
            "chair_name": "Jane Smith",
            "chair_email": "jane@smith.net",
            "runner_name": "John Doe",
            "runner_email": "john@doe.net",
        },
    ]

Since it contains volunteer names and emails, it should only be available to staff / superusers.

Use case: I have a script which generates a green-room schedule. This API endpoint will let me include the runner names and email addresses in that printout.

**Comment by dpoirier** [comment] 2015-08-17 13:35
Duplicate of #390.

**Closed by dpoirier** 2015-08-17 13:35 UTC
